language: csharp
Solution: ./DigitalLibraryApplication.sln
dist: trusty
mono: none
dotnet: 2.1.0
install:
    - dotnet restore
script:
    - dotnet build
    - dotnet test ./DigitalLibraryApplication/DigitalLibraryUnitTests.csproj

